// Code generated by internal/typegen from contract/v1/schema.json. DO NOT EDIT.

package insight

import "encoding/json"

var _ json.RawMessage

type AnalysisList struct {
	Analyses        []AnalysisRun `json:"analyses"`
	ContractVersion string        `json:"contractVersion"`
	SubjectID       string        `json:"subjectId"`
}

// Assumption: A typed assumption. Only OBSERVED_BASELINE may cite evidenceRefs as observed fact; other kinds cite sourceRefs.
type Assumption struct {
	AsOf         string   `json:"asOf"`
	EvidenceRefs []string `json:"evidenceRefs,omitempty"`
	ID           string   `json:"id"`
	Kind         string   `json:"kind"`
	SourceRefs   []string `json:"sourceRefs,omitempty"`
	Statement    string   `json:"statement"`
	ValidUntil   string   `json:"validUntil,omitempty"`
}

// AssumptionCheck: Whether later evidence kept an assumption. INVALIDATED requires evidenceRef.
type AssumptionCheck struct {
	AssumptionID string `json:"assumptionId"`
	EvidenceRef  string `json:"evidenceRef,omitempty"`
	Note         string `json:"note,omitempty"`
	Result       string `json:"result"`
}

type ColumnProfile struct {
	DistinctCapped bool     `json:"distinctCapped"`
	DistinctCount  int      `json:"distinctCount"`
	Max            string   `json:"max,omitempty"`
	Min            string   `json:"min,omitempty"`
	Name           string   `json:"name"`
	NonNullCount   int      `json:"nonNullCount"`
	NullCount      int      `json:"nullCount"`
	SampleValues   []string `json:"sampleValues"`
	Type           string   `json:"type"`
}

// CreateDatasetProfileRequest: Exactly one of csv (inline, at most 8 MiB) or documentId (an evidence document of the subject) is required.
type CreateDatasetProfileRequest struct {
	ContractVersion string     `json:"contractVersion"`
	Csv             string     `json:"csv,omitempty"`
	Dataset         DatasetRef `json:"dataset"`
	DocumentID      string     `json:"documentId,omitempty"`
	IdempotencyKey  string     `json:"idempotencyKey"`
}

// CreateScenarioSetRequest: Submit a curated scenario set as the next version.
type CreateScenarioSetRequest struct {
	ContractVersion string           `json:"contractVersion"`
	IdempotencyKey  string           `json:"idempotencyKey"`
	ScenarioSet     ScenarioSetDraft `json:"scenarioSet"`
}

// DatasetProfile: Deterministic, bounded metadata. Identical bytes give an identical profileFingerprint. Raw rows are never stored or returned.
type DatasetProfile struct {
	Columns            []ColumnProfile `json:"columns"`
	ContentSha256      string          `json:"contentSha256"`
	ContractVersion    string          `json:"contractVersion"`
	CreatedAt          string          `json:"createdAt"`
	Dataset            DatasetRef      `json:"dataset"`
	DocumentID         string          `json:"documentId,omitempty"`
	ProfileFingerprint string          `json:"profileFingerprint"`
	ProfileID          string          `json:"profileId"`
	ProfilerVersion    string          `json:"profilerVersion"`
	RowCount           int             `json:"rowCount"`
	SubjectID          string          `json:"subjectId"`
}

type DatasetRef struct {
	ID      string `json:"id"`
	Sha256  string `json:"sha256,omitempty"`
	Version string `json:"version"`
}

// EvaluateScenariosRequest: Evaluate a scenario set version against new observations.
type EvaluateScenariosRequest struct {
	AssumptionChecks []AssumptionCheck      `json:"assumptionChecks,omitempty"`
	ContractVersion  string                 `json:"contractVersion"`
	IdempotencyKey   string                 `json:"idempotencyKey"`
	IterationID      string                 `json:"iterationId,omitempty"`
	Observations     []IndicatorObservation `json:"observations,omitempty"`
}

type EvidenceChanges struct {
	Added   []string `json:"added"`
	Changed []string `json:"changed"`
	Removed []string `json:"removed"`
}

type EvidenceEvent struct {
	Detail      string   `json:"detail,omitempty"`
	GapIDs      []string `json:"gapIds,omitempty"`
	IterationID string   `json:"iterationId"`
	Kind        string   `json:"kind"`
	Reference   string   `json:"reference"`
	Sequence    int      `json:"sequence"`
}

type ExecutionAxisDiff struct {
	Changes []FieldChange `json:"changes"`
	State   string        `json:"state"`
}

type ExecutionProfileInfo struct {
	Available   bool   `json:"available"`
	Description string `json:"description"`
	Profile     string `json:"profile"`
}

// ExecutionProfileResolution: Which profile a run used and why. AUTO resolves deterministically from input shape; an unavailable profile fails with EXECUTION_PROFILE_UNAVAILABLE instead of downgrading. Recorded in provenance.execution, not in the execution fingerprint.
type ExecutionProfileResolution struct {
	Reason          string `json:"reason"`
	Requested       string `json:"requested"`
	Resolved        string `json:"resolved"`
	StrategyVersion string `json:"strategyVersion"`
}

type FieldChange struct {
	Field string `json:"field"`
	From  string `json:"from"`
	To    string `json:"to"`
}

// FiredFalsification: A falsification condition that fired on evidence.
type FiredFalsification struct {
	Condition     string `json:"condition"`
	EvidenceRef   string `json:"evidenceRef"`
	ExpectationID string `json:"expectationId"`
	ScenarioID    string `json:"scenarioId"`
}

type HypothesisEvent struct {
	Attribution                    string   `json:"attribution"`
	EvidenceRefs                   []string `json:"evidenceRefs,omitempty"`
	Evolution                      string   `json:"evolution"`
	HypothesisID                   string   `json:"hypothesisId"`
	InvalidatesPriorInterpretation bool     `json:"invalidatesPriorInterpretation"`
	IterationID                    string   `json:"iterationId"`
	Reason                         string   `json:"reason"`
	Sequence                       int      `json:"sequence"`
}

// IndicatorObservation: A later observation for one expectation. CONSISTENT/CONTRADICTS require evidenceRef. Observations at or before the set was created cannot test it.
type IndicatorObservation struct {
	EvidenceRef   string `json:"evidenceRef,omitempty"`
	ExpectationID string `json:"expectationId"`
	Note          string `json:"note,omitempty"`
	ObservedAt    string `json:"observedAt"`
	Outcome       string `json:"outcome"`
}

type InputAxisDiff struct {
	DatasetHashesAdded   []string `json:"datasetHashesAdded"`
	DatasetHashesRemoved []string `json:"datasetHashesRemoved"`
	DatasetsAdded        []string `json:"datasetsAdded"`
	DatasetsRemoved      []string `json:"datasetsRemoved"`
	DocumentsAdded       []string `json:"documentsAdded"`
	DocumentsRemoved     []string `json:"documentsRemoved"`
	State                string   `json:"state"`
}

// InputSource: Additive input variant (#90). kind RAW_ARTIFACT registers an engine-verified reference. With preparation, the bytes are prepared into an Analytical Artifact when an analysis runs on STANDARD or HEAVY; without it the reference is recorded for provenance only and never analyzed as text.
type InputSource struct {
	ExternalRef string           `json:"externalRef"`
	Kind        string           `json:"kind"`
	Metadata    json.RawMessage  `json:"metadata,omitempty"`
	Preparation *PreparationSpec `json:"preparation,omitempty"`
	RawArtifact RawArtifactRef   `json:"rawArtifact"`
	Title       string           `json:"title,omitempty"`
}

type InputSourceReceipt struct {
	DocumentID         string `json:"documentId"`
	ExternalRef        string `json:"externalRef"`
	Preparation        string `json:"preparation"`
	PreparedArtifactID string `json:"preparedArtifactId,omitempty"`
	Sha256             string `json:"sha256"`
	SizeBytes          int    `json:"sizeBytes"`
	Status             string `json:"status"`
	VerifiedBy         string `json:"verifiedBy"`
}

type InsightMatch struct {
	Changes       []FieldChange `json:"changes"`
	FromInsightID string        `json:"fromInsightId"`
	Method        string        `json:"method"`
	Score         float64       `json:"score"`
	ToInsightID   string        `json:"toInsightId"`
}

type InsightResultDiff struct {
	Added   []string       `json:"added"`
	Matched []InsightMatch `json:"matched"`
	Removed []string       `json:"removed"`
}

type InsightVersion struct {
	Attribution string   `json:"attribution"`
	Explanation []string `json:"explanation,omitempty"`
	InsightIDs  []string `json:"insightIds,omitempty"`
	IterationID string   `json:"iterationId"`
	Sequence    int      `json:"sequence"`
}

// InstrumentChange: Execution fingerprint of consecutive iterations' analyses. UNKNOWN means not recorded, never SAME.
type InstrumentChange struct {
	ChangedFields   []string `json:"changedFields,omitempty"`
	Execution       string   `json:"execution"`
	FromIterationID string   `json:"fromIterationId"`
	ToIterationID   string   `json:"toIterationId"`
}

type MetricDelta struct {
	Delta  json.RawMessage `json:"delta"`
	From   json.RawMessage `json:"from"`
	Metric string          `json:"metric"`
	To     json.RawMessage `json:"to"`
}

type MetricRange struct {
	Max    float64 `json:"max"`
	Metric string  `json:"metric"`
	Min    float64 `json:"min"`
}

// ModelRouting: Per-run model binding extension point (#65): stages a caller may bind and the models the engine operator allowed (the configured model is always allowed). The engine never chooses models itself; bindings are execution config recorded in provenance.execution.llm.models and the execution fingerprint, and never change research semantics.
type ModelRouting struct {
	AllowedModels []string `json:"allowedModels"`
	Stages        []string `json:"stages"`
}

// ObservationWindow: As-of boundary of a longitudinal iteration (#71). A later iteration may not use an earlier asOf than one already recorded.
type ObservationWindow struct {
	AsOf  string `json:"asOf"`
	Basis string `json:"basis,omitempty"`
	End   string `json:"end,omitempty"`
	Note  string `json:"note,omitempty"`
	Start string `json:"start,omitempty"`
}

type PlanMove struct {
	Classifications []string `json:"classifications,omitempty"`
	FromBucket      string   `json:"fromBucket,omitempty"`
	Name            string   `json:"name"`
	Rationale       string   `json:"rationale"`
	Role            string   `json:"role,omitempty"`
	ToBucket        string   `json:"toBucket"`
}

type PlanProposer struct {
	Actor string `json:"actor,omitempty"`
	Kind  string `json:"kind"`
	Model string `json:"model,omitempty"`
}

// PreparationSpec: Declarative deterministic preparation of a raw CSV into an Analytical Artifact. Unknown fields are rejected. Sums are exact, so partitioned (HEAVY) and single-pass (STANDARD) preparation produce the same artifact.
type PreparationSpec struct {
	DimensionColumns []string          `json:"dimensionColumns,omitempty"`
	Kind             string            `json:"kind"`
	Metrics          []json.RawMessage `json:"metrics"`
	Period           json.RawMessage   `json:"period,omitempty"`
	PeriodColumn     string            `json:"periodColumn,omitempty"`
	Population       json.RawMessage   `json:"population"`
}

// RawArtifactRef: Reference to raw bytes held outside the engine. sha256 and sizeBytes are claims: the engine streams the bytes, measures them itself and rejects a mismatch with INPUT_VERIFICATION_FAILED. Supported URI schemes depend on the resolvers the engine is configured with (Core ships file:<relative path> under a configured root).
type RawArtifactRef struct {
	MediaType string `json:"mediaType"`
	Name      string `json:"name,omitempty"`
	Sha256    string `json:"sha256,omitempty"`
	SizeBytes *int   `json:"sizeBytes,omitempty"`
	Uri       string `json:"uri"`
	Version   string `json:"version,omitempty"`
}

// ReEvaluationRecord: Audit record attached to the iteration a re-evaluation created. Earlier iterations are never modified.
type ReEvaluationRecord struct {
	AffectedGapIDs             []string            `json:"affectedGapIds"`
	AffectedHypothesisIDs      []string            `json:"affectedHypothesisIds"`
	AffectedScenarioIDs        []string            `json:"affectedScenarioIds,omitempty"`
	AffectedScenarioSetID      string              `json:"affectedScenarioSetId,omitempty"`
	CorrelationKey             string              `json:"correlationKey"`
	EvidenceChanges            EvidenceChanges     `json:"evidenceChanges"`
	ExecutionFingerprintAfter  string              `json:"executionFingerprintAfter,omitempty"`
	ExecutionFingerprintBefore string              `json:"executionFingerprintBefore,omitempty"`
	InputFingerprintAfter      string              `json:"inputFingerprintAfter,omitempty"`
	InputFingerprintBefore     string              `json:"inputFingerprintBefore,omitempty"`
	Note                       string              `json:"note,omitempty"`
	PreviousIterationID        string              `json:"previousIterationId"`
	RecordedAt                 string              `json:"recordedAt"`
	Scope                      string              `json:"scope"`
	ScopeReason                string              `json:"scopeReason"`
	Trigger                    ReEvaluationTrigger `json:"trigger"`
}

// ReEvaluationRequest: Re-evaluate a research run because new evidence arrived (#74). analysisId names a completed analysis run over the new evidence. The engine schedules nothing itself.
type ReEvaluationRequest struct {
	AffectedGapIDs      []string            `json:"affectedGapIds,omitempty"`
	AnalysisID          string              `json:"analysisId"`
	ContractVersion     string              `json:"contractVersion"`
	CorrelationKey      string              `json:"correlationKey"`
	EvidenceChanges     EvidenceChanges     `json:"evidenceChanges"`
	IdempotencyKey      string              `json:"idempotencyKey"`
	Note                string              `json:"note,omitempty"`
	PreviousIterationID string              `json:"previousIterationId"`
	Trigger             ReEvaluationTrigger `json:"trigger"`
}

type ReEvaluationResult struct {
	ContractVersion string             `json:"contractVersion"`
	ReEvaluation    ReEvaluationRecord `json:"reEvaluation"`
	ResearchRunID   string             `json:"researchRunId"`
	Result          ResearchResult     `json:"result"`
	Status          string             `json:"status"`
	SubjectID       string             `json:"subjectId"`
}

type ReEvaluationTrigger struct {
	Kind   string `json:"kind"`
	Source string `json:"source,omitempty"`
}

type RepeatGroup struct {
	AnalysisIDs    []string      `json:"analysisIds"`
	Key            string        `json:"key"`
	Metrics        []MetricRange `json:"metrics"`
	Runs           int           `json:"runs"`
	VariationKnown bool          `json:"variationKnown"`
}

type ResearchRunList struct {
	ContractVersion string               `json:"contractVersion"`
	ResearchRuns    []ResearchRunSummary `json:"researchRuns"`
	SubjectID       string               `json:"subjectId"`
}

type ResearchRunSummary struct {
	CreatedAt               string `json:"createdAt"`
	IterationCount          int    `json:"iterationCount"`
	LatestIterationID       string `json:"latestIterationId"`
	LatestIterationSequence int    `json:"latestIterationSequence"`
	Question                string `json:"question"`
	ResearchRunID           string `json:"researchRunId"`
}

// ResearchTimeline: Longitudinal read model of a research run (#71). Evidence/world changes and instrument (engine/model/prompt/rules) changes are separate arrays and are never merged. Derived from immutable iterations; historical entries never change when iterations are appended.
type ResearchTimeline struct {
	AsOf              string                     `json:"asOf,omitempty"`
	ContractVersion   string                     `json:"contractVersion"`
	EvidenceEvents    []EvidenceEvent            `json:"evidenceEvents"`
	HypothesisEvents  []HypothesisEvent          `json:"hypothesisEvents"`
	InsightVersions   []InsightVersion           `json:"insightVersions"`
	InstrumentChanges []InstrumentChange         `json:"instrumentChanges"`
	Iterations        []TimelineIteration        `json:"iterations"`
	Limitations       []string                   `json:"limitations"`
	ObservationDeltas []TimelineObservationDelta `json:"observationDeltas"`
	Question          string                     `json:"question"`
	ResearchRunID     string                     `json:"researchRunId"`
	SubjectID         string                     `json:"subjectId"`
}

type ReviseSelectionPlanRequest struct {
	Actor           string     `json:"actor"`
	ContractVersion string     `json:"contractVersion"`
	IdempotencyKey  string     `json:"idempotencyKey"`
	Moves           []PlanMove `json:"moves"`
}

// RunComparison: Non-persistent comparison of two analysis runs of one subject (#83). It attributes a result delta to the input or execution axis. It never judges which run is better and never claims a cause.
type RunComparison struct {
	Attribution  string            `json:"attribution"`
	Execution    ExecutionAxisDiff `json:"execution"`
	Explanation  []string          `json:"explanation"`
	From         RunRef            `json:"from"`
	Input        InputAxisDiff     `json:"input"`
	Insights     InsightResultDiff `json:"insights"`
	Metrics      []MetricDelta     `json:"metrics"`
	RepeatGroups []RepeatGroup     `json:"repeatGroups"`
	To           RunRef            `json:"to"`
}

type RunComparisonResult struct {
	Comparison      RunComparison `json:"comparison"`
	ContractVersion string        `json:"contractVersion"`
	SubjectID       string        `json:"subjectId"`
}

type RunRef struct {
	AnalysisID           string `json:"analysisId"`
	CreatedAt            string `json:"createdAt"`
	ExecutionFingerprint string `json:"executionFingerprint,omitempty"`
	InputFingerprint     string `json:"inputFingerprint,omitempty"`
	Status               string `json:"status"`
}

// ScaffoldScenarioSetRequest: Draft scenarios deterministically from an iteration's competing hypotheses. Baseline and horizon are required.
type ScaffoldScenarioSetRequest struct {
	Baseline        ScenarioBaseline `json:"baseline"`
	ContractVersion string           `json:"contractVersion"`
	Horizon         ScenarioHorizon  `json:"horizon"`
	IdempotencyKey  string           `json:"idempotencyKey"`
	IterationID     string           `json:"iterationId,omitempty"`
}

// Scenario: One possible future branch. At least one expectation must be testable after the baseline.
type Scenario struct {
	AffectedDimensions        []string              `json:"affectedDimensions,omitempty"`
	Assumptions               []Assumption          `json:"assumptions"`
	DerivedFromHypothesisID   string                `json:"derivedFromHypothesisId,omitempty"`
	DisconfirmingObservations []string              `json:"disconfirmingObservations,omitempty"`
	EvidenceRefs              []string              `json:"evidenceRefs,omitempty"`
	Expectations              []ScenarioExpectation `json:"expectations"`
	Horizon                   ScenarioHorizon       `json:"horizon"`
	ID                        string                `json:"id"`
	Limitations               []string              `json:"limitations,omitempty"`
	Mechanisms                []string              `json:"mechanisms,omitempty"`
	Probability               *ScenarioProbability  `json:"probability,omitempty"`
	Title                     string                `json:"title"`
	UnresolvedGapIDs          []string              `json:"unresolvedGapIds,omitempty"`
}

// ScenarioAnalysis: Scenario history of a research run. Empty lists when none exist; scenarios are never synthesized.
type ScenarioAnalysis struct {
	ContractVersion   string               `json:"contractVersion"`
	CurrentEvaluation *ScenarioEvaluation  `json:"currentEvaluation,omitempty"`
	CurrentSet        *ScenarioSet         `json:"currentSet,omitempty"`
	Evaluations       []ScenarioEvaluation `json:"evaluations"`
	ResearchRunID     string               `json:"researchRunId"`
	Sets              []ScenarioSet        `json:"sets"`
}

// ScenarioBaseline: Observed baseline all scenarios branch from. asOf is required.
type ScenarioBaseline struct {
	AsOf         string   `json:"asOf"`
	Description  string   `json:"description"`
	EvidenceRefs []string `json:"evidenceRefs,omitempty"`
}

// ScenarioDelta: What new evidence changed. It ranks nothing and never names a most likely future.
type ScenarioDelta struct {
	AssumptionsInvalidated []string               `json:"assumptionsInvalidated,omitempty"`
	Contradicted           []ScenarioStatusChange `json:"contradicted,omitempty"`
	Explanation            []string               `json:"explanation,omitempty"`
	FalsificationsFired    []FiredFalsification   `json:"falsificationsFired,omitempty"`
	FromEvaluationID       string                 `json:"fromEvaluationId,omitempty"`
	NewlyRequiredEvidence  []string               `json:"newlyRequiredEvidence,omitempty"`
	Strengthened           []ScenarioStatusChange `json:"strengthened,omitempty"`
	ToEvaluationID         string                 `json:"toEvaluationId"`
	Unchanged              []string               `json:"unchanged,omitempty"`
	Weakened               []ScenarioStatusChange `json:"weakened,omitempty"`
}

// ScenarioEvaluation: Append-only evaluation of one set version; carries forward earlier observations.
type ScenarioEvaluation struct {
	AssumptionChecks []AssumptionCheck      `json:"assumptionChecks,omitempty"`
	DataRequirements []json.RawMessage      `json:"dataRequirements,omitempty"`
	Delta            ScenarioDelta          `json:"delta"`
	EvaluatedAt      string                 `json:"evaluatedAt"`
	ID               string                 `json:"id"`
	IterationID      string                 `json:"iterationId,omitempty"`
	Observations     []IndicatorObservation `json:"observations"`
	ResearchRunID    string                 `json:"researchRunId"`
	ScenarioSetID    string                 `json:"scenarioSetId"`
	SetVersion       int                    `json:"setVersion"`
	States           []ScenarioState        `json:"states"`
}

// ScenarioEvaluationResult: A stored scenario evaluation.
type ScenarioEvaluationResult struct {
	ContractVersion string             `json:"contractVersion"`
	Evaluation      ScenarioEvaluation `json:"evaluation"`
	ResearchRunID   string             `json:"researchRunId"`
}

// ScenarioExpectation: Frozen, falsifiable statement about a future observation.
type ScenarioExpectation struct {
	Direction                       string      `json:"direction,omitempty"`
	FalsificationCondition          string      `json:"falsificationCondition"`
	ID                              string      `json:"id"`
	Indicator                       string      `json:"indicator"`
	ObservationWindow               TimeWindow  `json:"observationWindow"`
	ObservedDataAvailableAtCreation bool        `json:"observedDataAvailableAtCreation"`
	Provenance                      string      `json:"provenance"`
	Range                           *ValueRange `json:"range,omitempty"`
	SourceRefs                      []string    `json:"sourceRefs,omitempty"`
	Statement                       string      `json:"statement"`
}

// ScenarioHorizon: Forecast horizon of a scenario; end must be after the baseline asOf.
type ScenarioHorizon struct {
	End   string `json:"end"`
	Label string `json:"label"`
}

// ScenarioProbability: Caller-supplied probability with its basis and sources. The engine never generates one.
type ScenarioProbability struct {
	Basis      string   `json:"basis"`
	SourceRefs []string `json:"sourceRefs"`
	Value      float64  `json:"value"`
}

// ScenarioRelation: Explicit relation between branches; scenarios need not be mutually exclusive.
type ScenarioRelation struct {
	Kind        string   `json:"kind"`
	Note        string   `json:"note,omitempty"`
	ScenarioIDs []string `json:"scenarioIds"`
}

// ScenarioSet: Append-only scenario set version. Curating creates a new version.
type ScenarioSet struct {
	Baseline           ScenarioBaseline   `json:"baseline"`
	CreatedAt          string             `json:"createdAt"`
	FromIterationID    string             `json:"fromIterationId,omitempty"`
	ID                 string             `json:"id"`
	NonExhaustive      bool               `json:"nonExhaustive"`
	Origin             string             `json:"origin"`
	Question           string             `json:"question"`
	Relations          []ScenarioRelation `json:"relations,omitempty"`
	ResearchRunID      string             `json:"researchRunId"`
	Scenarios          []Scenario         `json:"scenarios"`
	SharedEvidenceRefs []string           `json:"sharedEvidenceRefs,omitempty"`
	Version            int                `json:"version"`
}

// ScenarioSetDraft: Scenario set submitted by a consumer; id, version and createdAt are assigned by the engine.
type ScenarioSetDraft struct {
	Baseline           ScenarioBaseline   `json:"baseline"`
	FromIterationID    string             `json:"fromIterationId,omitempty"`
	NonExhaustive      bool               `json:"nonExhaustive"`
	Origin             string             `json:"origin"`
	Question           string             `json:"question"`
	Relations          []ScenarioRelation `json:"relations,omitempty"`
	Scenarios          []Scenario         `json:"scenarios"`
	SharedEvidenceRefs []string           `json:"sharedEvidenceRefs,omitempty"`
}

// ScenarioSetResult: A stored scenario set version.
type ScenarioSetResult struct {
	ContractVersion string      `json:"contractVersion"`
	ResearchRunID   string      `json:"researchRunId"`
	ScenarioSet     ScenarioSet `json:"scenarioSet"`
	Skipped         []string    `json:"skipped,omitempty"`
}

// ScenarioState: Evidence state of one scenario at one evaluation.
type ScenarioState struct {
	LastEvaluatedAt string   `json:"lastEvaluatedAt"`
	Reasons         []string `json:"reasons,omitempty"`
	ScenarioID      string   `json:"scenarioId"`
	Status          string   `json:"status"`
}

// ScenarioStatusChange: Status movement of one scenario.
type ScenarioStatusChange struct {
	From       string `json:"from"`
	ScenarioID string `json:"scenarioId"`
	To         string `json:"to"`
}

// SelectionPlan: One immutable version. decisions lists every profiled column exactly once, in profile order. moves records how this version differs from its parent.
type SelectionPlan struct {
	ContractVersion    string             `json:"contractVersion"`
	CreatedAt          string             `json:"createdAt"`
	Decisions          []VariableDecision `json:"decisions"`
	Gaps               []TriageGapRef     `json:"gaps,omitempty"`
	HypothesisIDs      []string           `json:"hypothesisIds,omitempty"`
	Moves              []PlanMove         `json:"moves,omitempty"`
	ParentPlanID       string             `json:"parentPlanId,omitempty"`
	PlanID             string             `json:"planId"`
	ProcessingBoundary string             `json:"processingBoundary"`
	ProfileID          string             `json:"profileId"`
	Proposer           PlanProposer       `json:"proposer"`
	Question           string             `json:"question"`
	SubjectID          string             `json:"subjectId"`
	Version            int                `json:"version"`
}

type SelectionPlanList struct {
	ContractVersion string          `json:"contractVersion"`
	Plans           []SelectionPlan `json:"plans"`
	ProfileID       string          `json:"profileId"`
	SubjectID       string          `json:"subjectId"`
}

// TemporalOperationRequest: Stateless #73 temporal operation. Nothing is stored; the derived artifact is neutral evidence that may later be submitted with addEvidence.
type TemporalOperationRequest struct {
	Artifact        json.RawMessage `json:"artifact"`
	ContractVersion string          `json:"contractVersion"`
	Operation       json.RawMessage `json:"operation"`
}

type TemporalOperationResult struct {
	Artifact        json.RawMessage `json:"artifact"`
	ContractVersion string          `json:"contractVersion"`
}

// TimeWindow: Closed time window.
type TimeWindow struct {
	End   string `json:"end"`
	Start string `json:"start"`
}

type TimelineIteration struct {
	AnalysisID           string             `json:"analysisId,omitempty"`
	CarriedUncertainty   []string           `json:"carriedUncertainty,omitempty"`
	IterationID          string             `json:"iterationId"`
	ObservationWindow    *ObservationWindow `json:"observationWindow,omitempty"`
	PreviousIterationID  string             `json:"previousIterationId,omitempty"`
	Question             string             `json:"question"`
	Readiness            string             `json:"readiness"`
	RecordedAt           string             `json:"recordedAt"`
	ResolvedUncertainty  []string           `json:"resolvedUncertainty,omitempty"`
	Sequence             int                `json:"sequence"`
	Stopped              bool               `json:"stopped"`
	UnresolvedGapIDs     []string           `json:"unresolvedGapIds,omitempty"`
	WhatWeCannotConclude []string           `json:"whatWeCannotConclude,omitempty"`
}

type TimelineObservationDelta struct {
	Delta           json.RawMessage `json:"delta"`
	FromIterationID string          `json:"fromIterationId"`
	SeriesKey       string          `json:"seriesKey"`
	ToIterationID   string          `json:"toIterationId"`
}

type TriageGapRef struct {
	GapID              string   `json:"gapId"`
	Need               string   `json:"need"`
	RequiredDimensions []string `json:"requiredDimensions,omitempty"`
}

// TriageRequest: researchRunId adds the unresolved ResearchGaps and DataRequirements of that run's latest iteration to gaps (re-triage).
type TriageRequest struct {
	ContractVersion string         `json:"contractVersion"`
	Gaps            []TriageGapRef `json:"gaps,omitempty"`
	HypothesisIDs   []string       `json:"hypothesisIds,omitempty"`
	IdempotencyKey  string         `json:"idempotencyKey"`
	Question        string         `json:"question"`
	ResearchRunID   string         `json:"researchRunId,omitempty"`
	Triager         string         `json:"triager,omitempty"`
}

// ValueRange: Optional numeric range for a RANGE expectation.
type ValueRange struct {
	Max  *float64 `json:"max,omitempty"`
	Min  *float64 `json:"min,omitempty"`
	Unit string   `json:"unit,omitempty"`
}

type VariableDecision struct {
	Bucket          string   `json:"bucket"`
	Classifications []string `json:"classifications,omitempty"`
	LinkedGapIDs    []string `json:"linkedGapIds,omitempty"`
	Name            string   `json:"name"`
	Rationale       string   `json:"rationale"`
	Role            string   `json:"role,omitempty"`
}

var generatedWireTypes = map[string]any{
	"AnalysisList":                AnalysisList{},
	"Assumption":                  Assumption{},
	"AssumptionCheck":             AssumptionCheck{},
	"ColumnProfile":               ColumnProfile{},
	"CreateDatasetProfileRequest": CreateDatasetProfileRequest{},
	"CreateScenarioSetRequest":    CreateScenarioSetRequest{},
	"DatasetProfile":              DatasetProfile{},
	"DatasetRef":                  DatasetRef{},
	"EvaluateScenariosRequest":    EvaluateScenariosRequest{},
	"EvidenceChanges":             EvidenceChanges{},
	"EvidenceEvent":               EvidenceEvent{},
	"ExecutionAxisDiff":           ExecutionAxisDiff{},
	"ExecutionProfileInfo":        ExecutionProfileInfo{},
	"ExecutionProfileResolution":  ExecutionProfileResolution{},
	"FieldChange":                 FieldChange{},
	"FiredFalsification":          FiredFalsification{},
	"HypothesisEvent":             HypothesisEvent{},
	"IndicatorObservation":        IndicatorObservation{},
	"InputAxisDiff":               InputAxisDiff{},
	"InputSource":                 InputSource{},
	"InputSourceReceipt":          InputSourceReceipt{},
	"InsightMatch":                InsightMatch{},
	"InsightResultDiff":           InsightResultDiff{},
	"InsightVersion":              InsightVersion{},
	"InstrumentChange":            InstrumentChange{},
	"MetricDelta":                 MetricDelta{},
	"MetricRange":                 MetricRange{},
	"ModelRouting":                ModelRouting{},
	"ObservationWindow":           ObservationWindow{},
	"PlanMove":                    PlanMove{},
	"PlanProposer":                PlanProposer{},
	"PreparationSpec":             PreparationSpec{},
	"RawArtifactRef":              RawArtifactRef{},
	"ReEvaluationRecord":          ReEvaluationRecord{},
	"ReEvaluationRequest":         ReEvaluationRequest{},
	"ReEvaluationResult":          ReEvaluationResult{},
	"ReEvaluationTrigger":         ReEvaluationTrigger{},
	"RepeatGroup":                 RepeatGroup{},
	"ResearchRunList":             ResearchRunList{},
	"ResearchRunSummary":          ResearchRunSummary{},
	"ResearchTimeline":            ResearchTimeline{},
	"ReviseSelectionPlanRequest":  ReviseSelectionPlanRequest{},
	"RunComparison":               RunComparison{},
	"RunComparisonResult":         RunComparisonResult{},
	"RunRef":                      RunRef{},
	"ScaffoldScenarioSetRequest":  ScaffoldScenarioSetRequest{},
	"Scenario":                    Scenario{},
	"ScenarioAnalysis":            ScenarioAnalysis{},
	"ScenarioBaseline":            ScenarioBaseline{},
	"ScenarioDelta":               ScenarioDelta{},
	"ScenarioEvaluation":          ScenarioEvaluation{},
	"ScenarioEvaluationResult":    ScenarioEvaluationResult{},
	"ScenarioExpectation":         ScenarioExpectation{},
	"ScenarioHorizon":             ScenarioHorizon{},
	"ScenarioProbability":         ScenarioProbability{},
	"ScenarioRelation":            ScenarioRelation{},
	"ScenarioSet":                 ScenarioSet{},
	"ScenarioSetDraft":            ScenarioSetDraft{},
	"ScenarioSetResult":           ScenarioSetResult{},
	"ScenarioState":               ScenarioState{},
	"ScenarioStatusChange":        ScenarioStatusChange{},
	"SelectionPlan":               SelectionPlan{},
	"SelectionPlanList":           SelectionPlanList{},
	"TemporalOperationRequest":    TemporalOperationRequest{},
	"TemporalOperationResult":     TemporalOperationResult{},
	"TimeWindow":                  TimeWindow{},
	"TimelineIteration":           TimelineIteration{},
	"TimelineObservationDelta":    TimelineObservationDelta{},
	"TriageGapRef":                TriageGapRef{},
	"TriageRequest":               TriageRequest{},
	"ValueRange":                  ValueRange{},
	"VariableDecision":            VariableDecision{},
}
