// Command typegen writes types_gen.go: Go wire types for every object $def in
// contract/v1/schema.json that has no hand-written type in types.go.
//
//	go run ./internal/typegen
//
// Hand-written types stay authoritative for the original v0 surface; the
// drift test checks both against the pinned schema.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
)

type prop struct {
	Ref   string          `json:"$ref"`
	Type  json.RawMessage `json:"type"`
	Items *prop           `json:"items"`
	Props json.RawMessage `json:"properties"`
	AddP  json.RawMessage `json:"additionalProperties"`
	Desc  string          `json:"description"`
}

type def struct {
	Type       string                     `json:"type"`
	Desc       string                     `json:"description"`
	Properties map[string]json.RawMessage `json:"properties"`
	Required   []string                   `json:"required"`
}

func main() {
	out := flag.String("out", "types_gen.go", "output file")
	flag.Parse()
	raw, err := os.ReadFile("contract/v1/schema.json")
	check(err)
	var doc struct {
		Defs map[string]json.RawMessage `json:"$defs"`
	}
	check(json.Unmarshal(raw, &doc))
	handwritten := handwrittenTypes()

	var names []string
	defs := map[string]def{}
	for name, body := range doc.Defs {
		var d def
		check(json.Unmarshal(body, &d))
		defs[name] = d
		if d.Type == "object" && d.Properties != nil && !handwritten[name] {
			names = append(names, name)
		}
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("// Code generated by internal/typegen from contract/v1/schema.json. DO NOT EDIT.\n\npackage insight\n\nimport \"encoding/json\"\n\nvar _ json.RawMessage\n\n")
	for _, name := range names {
		d := defs[name]
		if d.Desc != "" {
			fmt.Fprintf(&b, "// %s: %s\n", name, oneLine(d.Desc))
		}
		fmt.Fprintf(&b, "type %s struct {\n", name)
		req := map[string]bool{}
		for _, r := range d.Required {
			req[r] = true
		}
		var fields []string
		for f := range d.Properties {
			fields = append(fields, f)
		}
		sort.Strings(fields)
		for _, f := range fields {
			var p prop
			check(json.Unmarshal(d.Properties[f], &p))
			goType := typeOf(p, defs, req[f])
			tag := f
			if !req[f] {
				tag += ",omitempty"
			}
			fmt.Fprintf(&b, "\t%s %s `json:%q`\n", exported(f), goType, tag)
		}
		b.WriteString("}\n\n")
	}
	b.WriteString("var generatedWireTypes = map[string]any{\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q: %s{},\n", name, name)
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	check(err)
	check(os.WriteFile(*out, src, 0o644))
}

func typeOf(p prop, defs map[string]def, required bool) string {
	if p.Ref != "" {
		name := strings.TrimPrefix(p.Ref, "#/$defs/")
		d := defs[name]
		switch {
		case d.Type == "object" && d.Properties != nil:
			if required {
				return name
			}
			return "*" + name
		case d.Type == "object":
			return "json.RawMessage"
		case d.Type == "string":
			return "string"
		}
		return "json.RawMessage"
	}
	var t string
	if json.Unmarshal(p.Type, &t) != nil {
		return "json.RawMessage" // union type
	}
	switch t {
	case "string":
		return "string"
	case "integer":
		if required {
			return "int"
		}
		return "*int"
	case "number":
		if required {
			return "float64"
		}
		return "*float64"
	case "boolean":
		if required {
			return "bool"
		}
		return "*bool"
	case "array":
		if p.Items == nil {
			return "[]json.RawMessage"
		}
		return "[]" + strings.TrimPrefix(typeOf(*p.Items, defs, true), "*")
	case "object":
		if p.Props == nil && len(p.AddP) > 0 {
			var ap prop
			if json.Unmarshal(p.AddP, &ap) == nil && string(ap.Type) == `"string"` {
				return "map[string]string"
			}
		}
		return "json.RawMessage"
	}
	return "json.RawMessage"
}

var nonWord = regexp.MustCompile(`[^A-Za-z0-9]+`)

func exported(s string) string {
	parts := nonWord.Split(s, -1)
	var out string
	for _, p := range parts {
		if p == "" {
			continue
		}
		out += strings.ToUpper(p[:1]) + p[1:]
	}
	for _, init := range []string{"Id", "Url", "Uri", "Sha256"} {
		if strings.HasSuffix(out, init) {
			out = strings.TrimSuffix(out, init) + strings.ToUpper(init[:1]) + init[1:]
		}
	}
	out = strings.ReplaceAll(out, "Id", "ID")
	out = strings.ReplaceAll(out, "IDentification", "Identification")
	out = strings.ReplaceAll(out, "IDempotency", "Idempotency")
	return out
}

func handwrittenTypes() map[string]bool {
	src, err := os.ReadFile("types.go")
	check(err)
	out := map[string]bool{}
	for _, m := range regexp.MustCompile(`(?m)^type (\w+) struct`).FindAllSubmatch(src, -1) {
		out[string(m[1])] = true
	}
	return out
}

func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
